import "~/styles/globals.css";

import { TRPCReactProvider } from "~/trpc/react";
import NavBar from "./components/nav";
import Footer from "./components/footer";
import { ModalProvider } from "~/contexts/ModalContext";

export const metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="Body h-fit overflow-x-hidden bg-gradient-to-b from-primary via-neutralLight to-neutralDark">
        <TRPCReactProvider>
          <ModalProvider>
            <NavBar />
            {children}
            <Footer />
          </ModalProvider>
        </TRPCReactProvider>
      </body>
    </html>
  );
}
